import { 
  Star, 
  Cpu, 
  Database, 
  Cloud, 
  Terminal, 
  Monitor, 
  Brain, 
  Radio, 
  Smartphone, 
  Activity, 
  Code, 
  Zap, 
  Server, 
  Flame, 
  Layers, 
  Smile, 
  Compass, 
  Clock, 
  Search, 
  GitBranch, 
  Settings, 
  Volume2, 
  VolumeX, 
  Play, 
  Mic, 
  Gamepad2, 
  Music, 
  Palette,
  Sparkles
} from 'lucide-react';

export const REGISTERED_PROVIDERS_STATIC_DATA = [
  // --- CHAT TAB ---
  { id: 'official_chat', tab: 'chat', name: 'Official Provider', desc: 'Official AI provider redirected to local inference module.', pricing: 'free', deployment: 'local', icon: Star, url: 'local' },
  { id: 'openrouter', tab: 'chat', name: 'OpenRouter', desc: 'Universal gateway for models. Highly customizable list.', pricing: 'paid', deployment: 'cloud', icon: Cpu, url: 'openrouter.ai' },
  { id: 'aihubmix', tab: 'chat', name: 'AIHubMix', desc: 'High strength API gateway. (Offers 10% discount).', pricing: 'paid', deployment: 'cloud', icon: Database, url: 'aihubmix.com' },
  { id: 'azure_openai', tab: 'chat', name: 'Azure OpenAI', desc: 'Enterprise-grade Chat GPT deployments on Microsoft Cloud.', pricing: 'paid', deployment: 'cloud', icon: Cloud, url: 'azure.microsoft.com' },
  { id: 'ollama', tab: 'chat', name: 'Ollama', desc: 'Run modern LLMs (Llama 3, Mistral) entirely Offline.', pricing: 'free', deployment: 'local', icon: Terminal, url: 'ollama.ai' },
  { id: 'lmstudio', tab: 'chat', name: 'LM Studio', desc: 'Local model serving UI and OpenAI-compatible server hosting.', pricing: 'free', deployment: 'local', icon: Monitor, url: 'lmstudio.ai' },
  { id: 'deepseek', tab: 'chat', name: 'DeepSeek', desc: 'High-performance reasoner models from DeepSeek. Highly precise.', pricing: 'paid', deployment: 'cloud', icon: Brain, url: 'deepseek.com' },
  { id: 'openai_compatible', tab: 'chat', name: 'OpenAI Compatible', desc: 'Standard generic OpenAI-compatible custom endpoints provider.', pricing: 'paid', deployment: 'cloud', icon: Radio, url: 'custom-endpoint' },
  { id: 'xiaomi_mimo_chat', tab: 'chat', name: 'Xiaomi MiMo', desc: 'MiMo AI gateway API integration for smart agents.', pricing: 'paid', deployment: 'cloud', icon: Smartphone, url: 'api.xiaomimimo.com' },
  { id: 'openai', tab: 'chat', name: 'OpenAI', desc: 'Standard GPT-4o and GPT-4o-mini instances. Core connector.', pricing: 'paid', deployment: 'cloud', icon: Radio, url: 'api.openai.com' },
  { id: 'anthropic', tab: 'chat', name: 'Anthropic', desc: 'Claude series models (Sonnet, Opus) reasoning powers.', pricing: 'paid', deployment: 'cloud', icon: Brain, url: 'anthropic.com' },
  { id: '302_ai', tab: 'chat', name: '302.AI', desc: 'Global API multiplexer routing backend service.', pricing: 'paid', deployment: 'cloud', icon: Activity, url: '302.ai' },
  { id: 'volc_coding', tab: 'chat', name: 'Volcengine Coding Plan', desc: 'Bytedance Volcengine developer developer coding plan API.', pricing: 'free', deployment: 'cloud', icon: Code, url: 'volcengine.com' },
  { id: 'byteplus', tab: 'chat', name: 'BytePlus', desc: 'Bytedance global cloud services platform.', pricing: 'paid', deployment: 'cloud', icon: Zap, url: 'byteplus.com' },
  { id: 'gemini', tab: 'chat', name: 'Google Gemini', desc: 'Default thinking core of Yuihime. Direct Google AI Studio SDK.', pricing: 'free', deployment: 'cloud', icon: Sparkles, url: 'gemini.google.com' },
  { id: 'byteplus_coding', tab: 'chat', name: 'BytePlus Coding Plan', desc: 'BytePlus developer code plan API model connector.', pricing: 'free', deployment: 'cloud', icon: Code, url: 'byteplus.com' },
  { id: 'n1n', tab: 'chat', name: 'n1n', desc: 'High-performance AI model API token broker provider.', pricing: 'paid', deployment: 'cloud', icon: Zap, url: 'n1n.ai' },
  { id: 'azure_ai_foundry', tab: 'chat', name: 'Azure AI Foundry', desc: 'Deploy fine-tuned and proprietary models in Microsoft Foundry.', pricing: 'paid', deployment: 'cloud', icon: Cloud, url: 'azure.microsoft.com' },
  { id: 'bedrock', tab: 'chat', name: 'Amazon Bedrock', desc: 'Hosted foundation models gateway by Amazon Web Services.', pricing: 'paid', deployment: 'cloud', icon: Server, url: 'aws.amazon.com/bedrock' },
  { id: 'cerebras', tab: 'chat', name: 'Cerebras', desc: 'Cerebras custom hardware powered ultra-low latency AI endpoints.', pricing: 'paid', deployment: 'cloud', icon: Brain, url: 'cerebras.ai' },
  { id: 'cloudflare_ai', tab: 'chat', name: 'Cloudflare Workers AI', desc: 'Run serverless Llama models on Cloudflare global edge network.', pricing: 'free', deployment: 'cloud', icon: Cloud, url: 'cloudflare.com' },
  { id: 'comet_api_chat', tab: 'chat', name: 'Comet API', desc: 'CometAPI multi-routing agent gateway standard endpoints.', pricing: 'paid', deployment: 'cloud', icon: Flame, url: 'CometAPI.com' },
  { id: 'featherless', tab: 'chat', name: 'Featherless AI', desc: 'Run any open-source models with dedicated cloud server allocation.', pricing: 'paid', deployment: 'cloud', icon: Layers, url: 'featherless.ai' },
  { id: 'fireworks', tab: 'chat', name: 'Fireworks.ai', desc: 'Ultra-low-latency hosted open source LLM inferences.', pricing: 'paid', deployment: 'cloud', icon: Sparkles, url: 'fireworks.ai' },
  { id: 'groq', tab: 'chat', name: 'Groq', desc: 'Groq LPU powered real-time split-second text generation.', pricing: 'paid', deployment: 'cloud', icon: Zap, url: 'groq.com' },
  { id: 'minimax', tab: 'chat', name: 'MiniMax', desc: 'MiniMax proprietary large language models with strong chat.', pricing: 'paid', deployment: 'cloud', icon: Smile, url: 'minimaxi.com' },
  { id: 'minimax_global', tab: 'chat', name: 'MiniMax Global', desc: 'MiniMax Global market developer model API gateway.', pricing: 'paid', deployment: 'cloud', icon: Smile, url: 'minimax.io' },
  { id: 'mistral', tab: 'chat', name: 'Mistral', desc: 'High-performance Mistral Large, Mixtral and Codestral models.', pricing: 'paid', deployment: 'cloud', icon: Compass, url: 'mistral.ai' },
  { id: 'modelscope', tab: 'chat', name: 'ModelScope', desc: 'Alibaba open source model hub endpoint inference services.', pricing: 'free', deployment: 'cloud', icon: Layers, url: 'modelscope.cn' },
  { id: 'moonshot', tab: 'chat', name: 'Moonshot AI', desc: 'Moonshot / Kimi models with massive long context window support.', pricing: 'paid', deployment: 'cloud', icon: Clock, url: 'moonshot.ai' },
  { id: 'novita', tab: 'chat', name: 'Novita', desc: 'Novita AI high performance model cloud compute backend.', pricing: 'paid', deployment: 'cloud', icon: Activity, url: 'novita.ai' },
  { id: 'perplexity', tab: 'chat', name: 'Perplexity', desc: 'Search-grounded online model generations with real-time web.', pricing: 'paid', deployment: 'cloud', icon: Search, url: 'perplexity.ai' },
  { id: 'together_ai', tab: 'chat', name: 'Together.ai', desc: 'High performance hosted open model server cluster pools.', pricing: 'paid', deployment: 'cloud', icon: GitBranch, url: 'together.ai' },
  { id: 'z_ai', tab: 'chat', name: 'Z.ai', desc: 'Developer specialized high reliability model proxy.', pricing: 'paid', deployment: 'cloud', icon: Settings, url: 'z.ai' },
  { id: 'xai', tab: 'chat', name: 'xAI', desc: 'Grok-beta real-time internet-informed model inference.', pricing: 'paid', deployment: 'cloud', icon: Activity, url: 'x.ai' },

  // --- SPEECH TAB ---
  { id: 'official_speech', tab: 'speech', name: 'Official Speech Provider', desc: 'Official text-to-speech redirected to local inference module.', pricing: 'free', deployment: 'local', icon: Volume2, url: 'local/speech' },
  { id: 'official_streaming_speech', tab: 'speech', name: 'Official Streaming Speech Provider', desc: 'Official low-latency text-to-speech redirected to local inference module.', pricing: 'free', deployment: 'local', icon: Volume2, url: 'local/streaming' },
  { id: 'none_speech', tab: 'speech', name: 'None', desc: 'No vocal audio output syntheses.', pricing: 'free', deployment: 'local', icon: VolumeX, url: 'none' },
  { id: 'browser_speech', tab: 'speech', name: 'Browser (Local)', desc: 'https://github.com/moeru-ai/xsai-transformers', pricing: 'free', deployment: 'local', icon: Play, url: 'browser' },
  { id: 'openai_speech', tab: 'speech', name: 'OpenAI', desc: 'Standard openai tts and tts-1-hd cloud vocal templates.', pricing: 'paid', deployment: 'cloud', icon: Radio, url: 'api.openai.com' },
  { id: 'openai_compatible_speech', tab: 'speech', name: 'OpenAI Compatible', desc: 'OpenAI Compatible speech synthesis proxy endpoints.', pricing: 'paid', deployment: 'cloud', icon: Radio, url: 'openai-compatible' },
  { id: 'elevenlabs', tab: 'speech', name: 'ElevenLabs', desc: 'Sleek vocal synthesis. Advanced high-fidelity voice profiles.', pricing: 'paid', deployment: 'cloud', icon: Volume2, url: 'elevenlabs.io' },
  { id: 'deepgram_speech', tab: 'speech', name: 'Deepgram', desc: 'Super-low latency Deepgram Aura text-to-speech synthesizer.', pricing: 'paid', deployment: 'cloud', icon: Mic, url: 'api.deepgram.com' },
  { id: 'azure_speech', tab: 'speech', name: 'Microsoft / Azure Speech', desc: 'Highly reliable Azure cognitive text-to-speech engine.', pricing: 'paid', deployment: 'cloud', icon: Cloud, url: 'speech.microsoft.com' },
  { id: 'bilibili_index_tts', tab: 'speech', name: 'Bilibili / IndexTTS', desc: 'https://index-tts.github.io/ open source vocal backend.', pricing: 'free', deployment: 'cloud', icon: Music, url: 'index-tts.github.io' },
  { id: 'alibaba_studio_speech', tab: 'speech', name: 'Alibaba Cloud Model Studio', desc: 'Alibaba CosyVoice high-fidelity voice cloned outputs.', pricing: 'paid', deployment: 'cloud', icon: Layers, url: 'bailian.console.aliyun.com' },
  { id: 'volcano_speech', tab: 'speech', name: 'Volcano Engine', desc: 'Bytedance Volcano text-to-speech engine outputs.', pricing: 'paid', deployment: 'cloud', icon: Flame, url: 'volcengine.com' },
  { id: 'minimax_speech', tab: 'speech', name: 'MiniMax Speech', desc: 'MiniMax highly expressive vocal models syntheses.', pricing: 'paid', deployment: 'cloud', icon: Smile, url: 'minimax.io' },
  { id: 'openrouter_speech', tab: 'speech', name: 'OpenRouter', desc: 'Synthesize voice using openrouter-supported integrations.', pricing: 'paid', deployment: 'cloud', icon: Cpu, url: 'openrouter.ai' },
  { id: 'xiaomi_mimo_speech', tab: 'speech', name: 'Xiaomi MiMo', desc: 'MiMo sound systems Cloud TTS.', pricing: 'paid', deployment: 'cloud', icon: Smartphone, url: 'api.xiaomimimo.com' },
  { id: 'comet_api_speech', tab: 'speech', name: 'Comet API', desc: 'CometAPI audio stream creation endpoints.', pricing: 'paid', deployment: 'cloud', icon: Flame, url: 'CometAPI.com' },
  { id: 'player2_speech', tab: 'speech', name: 'Player2', desc: 'Gaming voice and custom player styles.', pricing: 'paid', deployment: 'cloud', icon: Gamepad2, url: 'player2.game' },
  { id: 'kokoro_local', tab: 'speech', name: 'Kokoro TTS (Local)', desc: 'Local high quality text-to-speech using lighter Kokoro-82M.', pricing: 'free', deployment: 'local', icon: Volume2, url: 'kokoro-local' },
  { id: 'custom_api_speech', tab: 'speech', name: 'Custom AI TTS (Local/Web)', desc: 'Configure custom HTTP GET/POST endpoints (RVC, GPT-SoVITS, Web-TTS, or localhost).', pricing: 'free', deployment: 'local', icon: Radio, url: 'custom-tts' },

  // --- TRANSCRIPTION TAB ---
  { id: 'browser_hearing', tab: 'transcription', name: 'Browser (Local)', desc: 'https://github.com/moeru-ai/xsai-transformers web hearing.', pricing: 'free', deployment: 'local', icon: Play, url: 'browser' },
  { id: 'openai_whisper', tab: 'transcription', name: 'OpenAI', desc: 'Whisper 1 cloud-based voice transcription helper.', pricing: 'paid', deployment: 'cloud', icon: Radio, url: 'api.openai.com' },
  { id: 'openai_compatible_transcription', tab: 'transcription', name: 'OpenAI Compatible', desc: 'Send audio packets to compatible custom Whisper API gateways.', pricing: 'paid', deployment: 'cloud', icon: Radio, url: 'openai-compatible' },
  { id: 'aliyun_nls_transcription', tab: 'transcription', name: 'Aliyun NLS', desc: 'Alibaba Aliyun Natural Language Transcription service.', pricing: 'paid', deployment: 'cloud', icon: Layers, url: 'aliyun-nls' },
  { id: 'web_speech_api', tab: 'transcription', name: 'Web Speech API', desc: 'Browser-native STT (requires Chrome/Edge/Safari support).', pricing: 'free', deployment: 'local', icon: Mic, url: 'web-speech' },
  { id: 'comet_api_transcription', tab: 'transcription', name: 'Comet API', desc: 'CometAPI speech synthesis and transcribe streams.', pricing: 'paid', deployment: 'cloud', icon: Flame, url: 'CometAPI.com' },
  { id: 'xiaomi_mimo_transcription', tab: 'transcription', name: 'Xiaomi MiMo', desc: 'Audit streams and text mapping in MiMo cloud.', pricing: 'paid', deployment: 'cloud', icon: Smartphone, url: 'api.xiaomimimo.com' },

  // --- ARTISTRY TAB ---
  { id: 'comfyui', tab: 'artistry', name: 'ComfyUI', desc: 'Local image generation runner. SD & FLUX node paths.', pricing: 'free', deployment: 'local', icon: Palette, url: '127.0.0.1:8188' },
  { id: 'replicate', tab: 'artistry', name: 'Replicate', desc: 'Hosted diffusion & machine learning cloud pipelines.', pricing: 'paid', deployment: 'cloud', icon: Activity, url: 'replicate.com' },
  { id: 'nano_banana', tab: 'artistry', name: 'Nano Banana', desc: 'AIRI and Google AI Studio Image Preview visual service.', pricing: 'free', deployment: 'cloud', icon: Monitor, url: 'nano-banana' }
];
